// Scene modules load on demand, so each lives in its own chunk and only nearby scenes are in memory.
// Every factory is called as factory(ctx, sceneSpec) and returns { scene, camera, resize, update, ... }.

export const MODULES = {
  cosmos: () => import("./cosmos.js").then((m) => m.createCosmos),
  earth: () => import("./earth.js").then((m) => m.createEarth),
  eden: () => import("./eden.js").then((m) => m.createEden),
  maps: () => import("./maps.js").then((m) => m.create),
  cain: () => import("./cain.js").then((m) => m.create),
  flood: () => import("./flood.js").then((m) => m.create),
  babel: () => import("./babel.js").then((m) => m.create),
  promise: () => import("./promise.js").then((m) => m.create),
  sodom: () => import("./sodom.js").then((m) => m.create),
  moriah: () => import("./moriah.js").then((m) => m.create),
  bethel: () => import("./bethel.js").then((m) => m.create),
  peniel: () => import("./peniel.js").then((m) => m.create),
  tribes: () => import("./tribes.js").then((m) => m.create),
  joseph: () => import("./joseph.js").then((m) => m.create),
  egypt: () => import("./egypt.js").then((m) => m.create),
  bondage: () => import("./bondage.js").then((m) => m.create),
  bush: () => import("./bush.js").then((m) => m.create),
  plagues: () => import("./plagues.js").then((m) => m.create),
  redsea: () => import("./redsea.js").then((m) => m.create),
  sinai: () => import("./sinai.js").then((m) => m.create),
  jordan: () => import("./jordan.js").then((m) => m.create),
  jericho: () => import("./jericho.js").then((m) => m.create),
  judges: () => import("./judges.js").then((m) => m.create),
  ruth: () => import("./ruth.js").then((m) => m.create),
  shiloh: () => import("./shiloh.js").then((m) => m.create),
  elah: () => import("./elah.js").then((m) => m.create),
  david: () => import("./david.js").then((m) => m.create),
  temple: () => import("./temple.js").then((m) => m.create),
  carmel: () => import("./carmel.js").then((m) => m.create),
  isaiah: () => import("./isaiah.js").then((m) => m.create),
  fall: () => import("./fall.js").then((m) => m.create),
  babylon: () => import("./babylon.js").then((m) => m.create),
  chebar: () => import("./chebar.js").then((m) => m.create),
  bones: () => import("./bones.js").then((m) => m.create),
  daniel: () => import("./daniel.js").then((m) => m.create),
  return: () => import("./return.js").then((m) => m.create),
  nativity: () => import("./nativity.js").then((m) => m.create),
  baptism: () => import("./baptism.js").then((m) => m.create),
  temptation: () => import("./temptation.js").then((m) => m.create),
  galilee: () => import("./galilee.js").then((m) => m.create),
  passion: () => import("./passion.js").then((m) => m.create),
  risen: () => import("./risen.js").then((m) => m.create),
  pentecost: () => import("./pentecost.js").then((m) => m.create),
  patmos: () => import("./patmos.js").then((m) => m.create),
  throne: () => import("./throne.js").then((m) => m.create),
  newcreation: () => import("./newcreation.js").then((m) => m.create),
};
