"""Hand-curated knowledge for Joshua-Malachi: book metadata, narrative dating, regnal chronology,
explicit ages, dated events, sections, and unnamed individuals.

All Masoretic verse references use English versification (as indexed by TIPNR); differences from
Hebrew numbering are documented on the witnesses.
"""

# code, work_id, title, chapters, LXX title, has Dillmann Ge'ez (Octateuch), die-bibel code
BOOKS = [
    ("Jos", "joshua", "Joshua", 24, "Joshua (Iesous)", True, "JOS"),
    ("Jdg", "judges", "Judges", 21, "Judges", True, "JDG"),
    ("Rut", "ruth", "Ruth", 4, "Ruth", True, "RUT"),
    ("1Sa", "1-samuel", "1 Samuel", 31, "1 Reigns", False, "1SA"),
    ("2Sa", "2-samuel", "2 Samuel", 24, "2 Reigns", False, "2SA"),
    ("1Ki", "1-kings", "1 Kings", 22, "3 Reigns", False, "1KI"),
    ("2Ki", "2-kings", "2 Kings", 25, "4 Reigns", False, "2KI"),
    ("1Ch", "1-chronicles", "1 Chronicles", 29, "1 Supplements (Paraleipomenon)", False, "1CH"),
    ("2Ch", "2-chronicles", "2 Chronicles", 36, "2 Supplements (Paraleipomenon)", False, "2CH"),
    ("Ezr", "ezra", "Ezra", 10, "2 Esdras", False, "EZR"),
    ("Neh", "nehemiah", "Nehemiah", 13, "2 Esdras", False, "NEH"),
    ("Est", "esther", "Esther", 10, "Esther", False, "EST"),
    ("Job", "job", "Job", 42, "Job", False, "JOB"),
    ("Psa", "psalms", "Psalms", 150, "Psalms", False, "PSA"),
    ("Pro", "proverbs", "Proverbs", 31, "Proverbs", False, "PRO"),
    ("Ecc", "ecclesiastes", "Ecclesiastes", 12, "Ecclesiastes", False, "ECC"),
    ("Sng", "song-of-songs", "Song of Songs", 8, "Song of Songs", False, "SNG"),
    ("Isa", "isaiah", "Isaiah", 66, "Isaiah", False, "ISA"),
    ("Jer", "jeremiah", "Jeremiah", 52, "Jeremiah", False, "JER"),
    ("Lam", "lamentations", "Lamentations", 5, "Lamentations", False, "LAM"),
    ("Ezk", "ezekiel", "Ezekiel", 48, "Ezekiel", False, "EZK"),
    ("Dan", "daniel", "Daniel", 12, "Daniel", False, "DAN"),
    ("Hos", "hosea", "Hosea", 14, "Hosea", False, "HOS"),
    ("Jol", "joel", "Joel", 3, "Joel", False, "JOL"),
    ("Amo", "amos", "Amos", 9, "Amos", False, "AMO"),
    ("Oba", "obadiah", "Obadiah", 1, "Obadiah", False, "OBA"),
    ("Jon", "jonah", "Jonah", 4, "Jonah", False, "JON"),
    ("Mic", "micah", "Micah", 7, "Micah", False, "MIC"),
    ("Nam", "nahum", "Nahum", 3, "Nahum", False, "NAM"),
    ("Hab", "habakkuk", "Habakkuk", 3, "Habakkuk", False, "HAB"),
    ("Zep", "zephaniah", "Zephaniah", 3, "Zephaniah", False, "ZEP"),
    ("Hag", "haggai", "Haggai", 2, "Haggai", False, "HAG"),
    ("Zec", "zechariah", "Zechariah", 14, "Zechariah", False, "ZEC"),
    ("Mal", "malachi", "Malachi", 4, "Malachi", False, "MAL"),
]

# Versification notes recorded on each Masoretic witness when the English chapter division differs.
MT_VERSIFICATION_NOTES = {
    "1-kings": "English 1 Kings 4:21-34 = Masoretic 5:1-14; English 5:1-18 = Masoretic 5:15-32.",
    "1-chronicles": "English 1 Chronicles 6:1-15 = Masoretic 5:27-41; English 6:16-81 = Masoretic 6:1-66.",
    "nehemiah": "English Nehemiah 4:1-6 = Masoretic 3:33-38; English 4:7-23 = Masoretic 4:1-17.",
    "joel": "English Joel 2:28-32 = Masoretic 3:1-5; English Joel 3 = Masoretic Joel 4.",
    "malachi": "English Malachi 4:1-6 = Masoretic 3:19-24.",
    "psalms": "English verse numbers exclude superscriptions, which the Masoretic text often counts as verse 1.",
    "daniel": "English Daniel 4:1-3 = Masoretic 3:31-33; English 5:31 = Masoretic 6:1.",
    "isaiah": "English Isaiah 9:1-21 = Masoretic 8:23-9:20.",
    "ezekiel": "English Ezekiel 20:45-49 = Masoretic 21:1-5; English 21 = Masoretic 21:6-37.",
    "hosea": "English Hosea 1:10-2:23 = Masoretic 2:1-25; English 11:12-12:14 = Masoretic 12:1-15.",
    "jonah": "English Jonah 1:17 = Masoretic 2:1.",
    "micah": "English Micah 5:1 = Masoretic 4:14.",
    "nahum": "English Nahum 1:15 = Masoretic 2:1.",
    "zechariah": "English Zechariah 1:18-21 = Masoretic 2:1-4.",
    "2-samuel": "English 2 Samuel 18:33 = Masoretic 19:1.",
    "2-kings": "English 2 Kings 11:21 = Masoretic 12:1.",
    "2-chronicles": "English 2 Chronicles 2:1 = Masoretic 1:18; English 14:1 = Masoretic 13:23.",
    "1-samuel": "English 1 Samuel 20:42b = Masoretic 21:1; English 23:29 = Masoretic 24:1.",
    "job": "English Job 41:1-8 = Masoretic 40:25-32.",
    "ecclesiastes": "English Ecclesiastes 5:1 = Masoretic 4:17.",
    "song-of-songs": "English Song 6:13 = Masoretic 7:1.",
}

# Septuagint structural notes recorded on the Greek witnesses.
LXX_NOTES = {
    "jeremiah": "The Greek Jeremiah is about one-eighth shorter and places the oracles against the nations (Masoretic 46-51) after 25:13; chapter numbers from Masoretic 25:15 onward differ.",
    "psalms": "Greek Psalm numbering joins Masoretic 9-10 and 114-115 and splits 116 and 147; Masoretic 11-113 and 117-146 are one lower in the Greek. Psalm 151 is a separate work.",
    "esther": "Greek Esther contains six major additions (A-F) catalogued separately as Additions to Esther, and differs widely in wording.",
    "daniel": "Greek Daniel survives in Old Greek and Theodotion forms and includes Susanna, the Prayer of Azariah, and Bel and the Dragon, catalogued separately.",
    "job": "The Old Greek Job is roughly one-sixth shorter than the Masoretic text and adds an expanded speech by Job's wife and a closing note on Job's genealogy.",
    "1-kings": "3 Reigns has major rearrangements and additions (miscellanies after 2:35 and 2:46; an alternative Jeroboam account after 12:24) and differs in several regnal synchronisms.",
    "2-kings": "4 Reigns differs in several regnal synchronisms from the Masoretic text.",
    "1-samuel": "1 Reigns 17-18 is markedly shorter in the Vaticanus tradition followed by Rahlfs-Hanhart.",
    "proverbs": "Greek Proverbs orders chapters 24-31 differently and contains pluses and minuses.",
    "ezra": "Greek 2 Esdras 1-10 corresponds to Ezra; 1 Esdras is a separate parallel work.",
    "nehemiah": "Greek 2 Esdras 11-23 corresponds to Nehemiah 1-13.",
    "malachi": "English Malachi 4 corresponds to Greek Malachi 3:19-24, with the last verses in a different order.",
    "joel": "Greek Joel follows the Masoretic four-chapter division (English 2:28-3:21 = Greek 3-4).",
}

# Narrative setting (BCE) by chapter range, interpolated linearly: (book, first, last, year_at_first, year_at_last)
CHAPTER_DATES = [
    ("Jos", 1, 12, 1406, 1400), ("Jos", 13, 21, 1399, 1392), ("Jos", 22, 24, 1392, 1390),
    ("Jdg", 1, 2, 1390, 1380), ("Jdg", 3, 3, 1375, 1300), ("Jdg", 4, 5, 1240, 1200), ("Jdg", 6, 8, 1190, 1150),
    ("Jdg", 9, 9, 1150, 1147), ("Jdg", 10, 10, 1147, 1105), ("Jdg", 11, 12, 1105, 1080), ("Jdg", 13, 16, 1090, 1070),
    ("Jdg", 17, 21, 1385, 1370),
    ("Rut", 1, 4, 1130, 1115),
    ("1Sa", 1, 3, 1105, 1090), ("1Sa", 4, 7, 1080, 1060), ("1Sa", 8, 12, 1052, 1050), ("1Sa", 13, 15, 1048, 1030),
    ("1Sa", 16, 17, 1025, 1024), ("1Sa", 18, 26, 1023, 1013), ("1Sa", 27, 31, 1012, 1010),
    ("2Sa", 1, 4, 1010, 1004), ("2Sa", 5, 10, 1003, 995), ("2Sa", 11, 12, 993, 991), ("2Sa", 13, 19, 990, 979),
    ("2Sa", 20, 24, 978, 971),
    ("1Ki", 1, 2, 971, 970), ("1Ki", 3, 4, 970, 966), ("1Ki", 5, 8, 966, 959), ("1Ki", 9, 11, 959, 931),
    ("1Ki", 12, 14, 931, 913), ("1Ki", 15, 16, 913, 874), ("1Ki", 17, 19, 870, 860), ("1Ki", 20, 22, 857, 853),
    ("2Ki", 1, 2, 852, 851), ("2Ki", 3, 8, 850, 842), ("2Ki", 9, 10, 841, 841), ("2Ki", 11, 12, 841, 796),
    ("2Ki", 13, 13, 814, 796), ("2Ki", 14, 14, 796, 767), ("2Ki", 15, 15, 767, 732), ("2Ki", 16, 16, 735, 715),
    ("2Ki", 17, 17, 732, 722), ("2Ki", 18, 20, 715, 701), ("2Ki", 21, 21, 696, 640), ("2Ki", 22, 23, 640, 609),
    ("2Ki", 24, 24, 609, 597), ("2Ki", 25, 25, 588, 561),
    ("1Ch", 10, 10, 1010, 1010), ("1Ch", 11, 12, 1010, 1003), ("1Ch", 13, 16, 1003, 1000), ("1Ch", 17, 21, 1000, 975),
    ("1Ch", 22, 29, 975, 970),
    ("2Ch", 1, 9, 970, 931), ("2Ch", 10, 12, 931, 913), ("2Ch", 13, 13, 913, 911), ("2Ch", 14, 16, 911, 870),
    ("2Ch", 17, 20, 872, 848), ("2Ch", 21, 22, 848, 841), ("2Ch", 23, 24, 835, 796), ("2Ch", 25, 25, 796, 767),
    ("2Ch", 26, 26, 792, 740), ("2Ch", 27, 27, 750, 732), ("2Ch", 28, 28, 735, 715), ("2Ch", 29, 32, 715, 686),
    ("2Ch", 33, 33, 696, 640), ("2Ch", 34, 35, 640, 609), ("2Ch", 36, 36, 609, 538),
    ("Ezr", 1, 3, 538, 536), ("Ezr", 4, 6, 535, 515), ("Ezr", 7, 10, 458, 457),
    ("Neh", 1, 7, 445, 444), ("Neh", 8, 10, 444, 444), ("Neh", 11, 12, 444, 432), ("Neh", 13, 13, 432, 430),
    ("Est", 1, 1, 483, 483), ("Est", 2, 2, 479, 478), ("Est", 3, 10, 474, 473),
    ("Isa", 1, 12, 740, 732), ("Isa", 13, 35, 730, 705), ("Isa", 36, 39, 701, 701), ("Isa", 40, 66, 540, 540),
    ("Jer", 1, 20, 627, 605), ("Jer", 21, 24, 597, 588), ("Jer", 25, 25, 605, 605), ("Jer", 26, 26, 609, 609),
    ("Jer", 27, 29, 594, 593), ("Jer", 30, 33, 588, 587), ("Jer", 34, 34, 588, 588), ("Jer", 35, 36, 605, 604),
    ("Jer", 37, 39, 588, 586), ("Jer", 40, 44, 586, 580), ("Jer", 45, 45, 605, 605), ("Jer", 46, 51, 605, 594),
    ("Jer", 52, 52, 586, 561),
    ("Lam", 1, 5, 586, 586), ("Ezk", 1, 24, 593, 588), ("Ezk", 25, 39, 587, 585), ("Ezk", 40, 48, 573, 571),
    ("Dan", 1, 4, 605, 570), ("Dan", 5, 6, 539, 537), ("Dan", 7, 8, 553, 551), ("Dan", 9, 12, 539, 536),
    ("Hos", 1, 14, 755, 725), ("Jol", 1, 3, 830, 830), ("Amo", 1, 9, 760, 760), ("Oba", 1, 1, 586, 586),
    ("Jon", 1, 4, 780, 780), ("Mic", 1, 7, 740, 700), ("Nam", 1, 3, 650, 650), ("Hab", 1, 3, 605, 605),
    ("Zep", 1, 3, 630, 630), ("Hag", 1, 2, 520, 520), ("Zec", 1, 8, 520, 518), ("Zec", 9, 14, 500, 500),
    ("Mal", 1, 4, 450, 450),
]
# Chapters whose people are genealogical or retrospective rather than present in the narrative moment.
UNDATED_CHAPTERS = {("1Ch", c) for c in list(range(1, 10)) + list(range(23, 28))} | {("Neh", 12)} | {("Ezr", 2), ("Neh", 7)} | {
    ("Psa", c) for c in range(1, 151)} | {("Pro", c) for c in range(1, 32)} | {("Ecc", c) for c in range(1, 13)} | {
    ("Sng", c) for c in range(1, 9)} | {("Job", c) for c in range(1, 43)}

# Genealogical verses inside narrative books: ancestors listed here are not present at the narrative moment.
UNDATED_VERSES = {("Rut", 4, v) for v in range(17, 23)} | {("1Sa", 1, 1), ("1Sa", 9, 1), ("1Sa", 14, 3)} | {
    ("Ezr", 7, v) for v in range(1, 6)} | {("Ezr", 8, 2)} | {("Neh", 11, v) for v in range(3, 25)}
DESCENT_GAP = 60  # a "son" placed more than this many years after the parent's death or last appearance is recorded as a descendant

# TIPNR era -> grade-E birth range (BCE) used when no dated narrative chapter places the person.
ERA_BIRTH = {
    "the Patriarchs": (1950, 1750), "Egypt and Wilderness": (1700, 1480), "Conquest": (1470, 1420),
    "Egypt and Wilderness and Conquest": (1500, 1440), "before Israel's Monarchy": (1400, 1100),
    "United Monarchy": (1090, 990), "United Monarchyand Divided Monarchy": (1010, 950),
    "Divided Monarchy": (940, 640), "Exile and Return": (640, 480), "the New Testament": (60, 1),
    "before the Flood": (5000, 3500),
}
DEFAULT_SPAN = 65  # years from display birth to display death when nothing else is known
LEAD_IN = 35       # years between display birth and first narrative appearance
MAX_LIFE = 100     # display lives never exceed this without an explicit age
MAX_PARENT_AGE = 90  # a child is placed no more than this many years after a parent's birth
ERA_TOLERANCE = 50  # a first dated mention this far outside the TIPNR era is treated as retrospective

# ------------------------------------------------------------------ rulers with fixed reign windows
# name, disambiguating keyword (matched against TIPNR brief/description), accession BCE, reign end BCE,
# age at accession (or None), age verse, reign text, reign verse, display birth override, death override, note
RULERS = [
    ("Saul", "first king", 1050, 1010, None, None, None, "1 Samuel 13:1", 1080, 1010,
     "1 Samuel 13:1 is defective in the Masoretic text (age and reign length are incomplete); Acts 13:21 gives forty years. Reign dates are editorial."),
    ("Ish-bosheth", "", 1010, 1008, 40, "2 Samuel 2:10", "2 years", "2 Samuel 2:10", None, 1008, None),
    ("David", "king", 1010, 970, 30, "2 Samuel 5:4", "40 years (7 years 6 months at Hebron, 33 at Jerusalem)", "2 Samuel 5:4-5; 1 Kings 2:11", None, 970, None),
    ("Solomon", "", 970, 931, None, None, "40 years", "1 Kings 11:42; 2 Chronicles 9:30", 990, 931, None),
    ("Rehoboam", "", 931, 913, 41, "1 Kings 14:21; 2 Chronicles 12:13", "17 years", "1 Kings 14:21", None, 913, None),
    ("Abijah", "Rehoboam", 913, 911, None, None, "3 years", "1 Kings 15:2; 2 Chronicles 13:2", 950, 911, None),
    ("Asa", "king of judah", 911, 870, None, None, "41 years", "1 Kings 15:10", 930, 870, None),
    ("Jehoshaphat", "king of judah", 872, 848, 35, "1 Kings 22:42; 2 Chronicles 20:31", "25 years", "1 Kings 22:42", None, 848,
     "Accession taken at the start of a co-regency with Asa (872 BCE), a common harmonization."),
    ("Jehoram@1Ki.22.50-Mat", "", 853, 841, 32, "2 Kings 8:17; 2 Chronicles 21:5", "8 years", "2 Kings 8:17", 880, 841,
     "Age 32 is applied to the sole reign from 848 BCE after a co-regency beginning 853 BCE."),
    ("Ahaziah", "judah", 841, 841, 22, "2 Kings 8:26", "1 year", "2 Kings 8:26", None, 841,
     "2 Chronicles 22:2 (Masoretic) gives 42 years, which would make him older than his father; recorded as a variant."),
    ("Athaliah@2Ki.8.26-2Ch", "", 841, 835, None, None, "6 years", "2 Kings 11:3", 885, 835, None),
    ("Joash@2Ki.11.2-2Ch", "", 835, 796, 7, "2 Kings 11:21; 2 Chronicles 24:1", "40 years", "2 Kings 12:1", None, 796, None),
    ("Amaziah", "king of judah", 796, 767, 25, "2 Kings 14:2; 2 Chronicles 25:1", "29 years", "2 Kings 14:2", None, 767, None),
    ("Uzziah@2Ki.14.21-Mat", "", 792, 740, 16, "2 Kings 15:2; 2 Chronicles 26:3", "52 years", "2 Kings 15:2", None, 740,
     "Also called Azariah; accession counted from a co-regency with Amaziah (792 BCE). Isaiah 6:1 dates Isaiah's vision to the year he died."),
    ("Jotham", "king of judah", 750, 732, 25, "2 Kings 15:33; 2 Chronicles 27:1", "16 years", "2 Kings 15:33", None, 732, None),
    ("Ahaz", "king of judah", 735, 715, 20, "2 Kings 16:2; 2 Chronicles 28:1", "16 years", "2 Kings 16:2", None, 715, None),
    ("Hezekiah", "king of judah", 715, 686, 25, "2 Kings 18:2; 2 Chronicles 29:1", "29 years", "2 Kings 18:2", None, 686,
     "Fifteen years were added to his life after his illness (2 Kings 20:6; Isaiah 38:5)."),
    ("Manasseh", "king of judah", 696, 642, 12, "2 Kings 21:1; 2 Chronicles 33:1", "55 years", "2 Kings 21:1", None, 642,
     "Accession counted from a co-regency with Hezekiah (696 BCE)."),
    ("Amon", "king of judah", 642, 640, 22, "2 Kings 21:19; 2 Chronicles 33:21", "2 years", "2 Kings 21:19", None, 640, None),
    ("Josiah", "king of judah", 640, 609, 8, "2 Kings 22:1; 2 Chronicles 34:1", "31 years", "2 Kings 22:1", None, 609, None),
    ("Jehoahaz", "josiah", 609, 609, 23, "2 Kings 23:31; 2 Chronicles 36:2", "3 months", "2 Kings 23:31", None, 600,
     "Died in Egypt (2 Kings 23:34); the death year is editorial."),
    ("Jehoiakim", "", 609, 598, 25, "2 Kings 23:36; 2 Chronicles 36:5", "11 years", "2 Kings 23:36", None, 598, None),
    ("Jehoiachin", "", 598, 597, 18, "2 Kings 24:8", "3 months", "2 Kings 24:8", None, 560,
     "2 Chronicles 36:9 (Masoretic) gives age 8 and a reign of 3 months 10 days. Released in Babylon in 561 BCE (2 Kings 25:27); death year editorial."),
    ("Zedekiah", "last king", 597, 586, 21, "2 Kings 24:18; 2 Chronicles 36:11; Jeremiah 52:1", "11 years", "2 Kings 24:18", None, 585,
     "Blinded and taken to Babylon, where he died in prison (Jeremiah 52:11); death year editorial."),
    # Israel
    ("Jeroboam", "first king", 931, 910, None, None, "22 years", "1 Kings 14:20", 960, 910, None),
    ("Nadab", "jeroboam", 910, 909, None, None, "2 years", "1 Kings 15:25", 935, 909, None),
    ("Baasha", "", 909, 886, None, None, "24 years", "1 Kings 15:33", 940, 886, None),
    ("Elah", "baasha", 886, 885, None, None, "2 years", "1 Kings 16:8", 915, 885, None),
    ("Zimri", "seven days", 885, 885, None, None, "7 days", "1 Kings 16:15", 920, 885, None),
    ("Tibni", "", 885, 880, None, None, None, "1 Kings 16:21-22", 920, 880, "Rival of Omri; the text gives no reign length."),
    ("Omri", "king of israel", 885, 874, None, None, "12 years", "1 Kings 16:23", 920, 874, None),
    ("Ahab", "king of israel", 874, 853, None, None, "22 years", "1 Kings 16:29", 905, 853, None),
    ("Ahaziah", "israel", 853, 852, None, None, "2 years", "1 Kings 22:51", 875, 852, None),
    ("Joram@2Ki.1.17-2Ch", "", 852, 841, None, None, "12 years", "2 Kings 3:1", 873, 841, "Also called Joram."),
    ("Jehu", "king of israel", 841, 814, None, None, "28 years", "2 Kings 10:36", 885, 814, None),
    ("Jehoahaz", "jehu", 814, 798, None, None, "17 years", "2 Kings 13:1", 862, 798, None),
    ("Joash@2Ki.13.9-Amo", "", 798, 782, None, None, "16 years", "2 Kings 13:10", 840, 782, "Also called Joash. His display birth is set early enough to father Jeroboam II, whose co-regency began in 793 BCE."),
    ("Jeroboam", "jehoash", 793, 753, None, None, "41 years", "2 Kings 14:23", 815, 753, "Jeroboam II; accession counted from a co-regency (793 BCE)."),
    ("Zechariah@2Ki.14.29-", "", 753, 753, None, None, "6 months", "2 Kings 15:8", 780, 753, None),
    ("Shallum@2Ki.15.10-", "", 752, 752, None, None, "1 month", "2 Kings 15:13", 790, 752, None),
    ("Menahem", "", 752, 742, None, None, "10 years", "2 Kings 15:17", 790, 742, None),
    ("Pekahiah", "", 742, 740, None, None, "2 years", "2 Kings 15:23", 770, 740, None),
    ("Pekah", "", 752, 732, None, None, "20 years", "2 Kings 15:27", 780, 732,
     "The 20 years are commonly counted from a rival reign in Gilead overlapping Menahem."),
    ("Hoshea", "king of israel", 732, 723, None, None, "9 years", "2 Kings 17:1", 760, 720,
     "Imprisoned by Shalmaneser (2 Kings 17:4); fate and death year unknown."),
    # Foreign rulers (external chronology)
    ("Hiram@2Sa.5.11-2Ch", "", 980, 947, None, None, None, None, 1005, 947, None),
    ("Shishak", "", 945, 924, None, None, None, None, 975, 924, "Shoshenq I of Egypt (external identification)."),
    ("Hazael", "", 842, 796, None, None, None, None, 870, 796, None),
    ("Tiglath-pileser", "", 745, 727, None, None, None, None, 785, 727, "Tiglath-pileser III, also called Pul (2 Kings 15:19)."),
    ("Shalmaneser", "", 727, 722, None, None, None, None, 765, 722, "Shalmaneser V."),
    ("sargon-ii", "", 722, 705, None, None, None, None, 765, 705, "Sargon II (Isaiah 20:1)."),
    ("Sennacherib", "", 705, 681, None, None, None, None, 745, 681, "Killed by his sons (2 Kings 19:37)."),
    ("Esarhaddon", "", 681, 669, None, None, None, None, 713, 669, None),
    ("Tirhakah", "", 690, 664, None, None, None, None, 720, 664, "Taharqa of Egypt and Cush."),
    ("Neco", "", 610, 595, None, None, None, None, 640, 595, "Necho II of Egypt."),
    ("Hophra", "", 589, 570, None, None, None, None, 620, 570, "Apries of Egypt (Jeremiah 44:30)."),
    ("Nebuchadnezzar", "", 605, 562, None, None, None, None, 634, 562, "Nebuchadnezzar II of Babylon."),
    ("Evil-merodach", "", 562, 560, None, None, None, None, 595, 560, "Amel-Marduk of Babylon."),
    ("Belshazzar", "", 553, 539, None, None, None, None, 580, 539, "Co-regent with Nabonidus; killed the night Babylon fell (Daniel 5:30)."),
    ("Cyrus", "", 559, 530, None, None, None, None, 600, 530, "Cyrus II; conquered Babylon in 539 BCE."),
    ("Darius@Dan.5.31-", "", 539, 537, 62, "Daniel 5:31", None, None, None, 535,
     "Identity with a known ruler is debated (Gubaru, Cyrus, or Cyaxares are proposed); dates are editorial."),
    ("Darius@Ezr.4.5-Zec", "", 522, 486, None, None, None, None, 550, 486, "Darius I Hystaspes (Haggai, Zechariah, Ezra 4-6)."),
    ("Ahasuerus", "esther", 486, 465, None, None, None, None, 518, 465, "Usually identified with Xerxes I; the identification is editorial."),
    ("Artaxerxes", "", 465, 424, None, None, None, None, 490, 424, "Artaxerxes I Longimanus (Ezra 7; Nehemiah 2)."),
]

# ------------------------------------------------------------------ other explicit ages and durations (MT)
# name, keyword, predicate, value (years), verse, note, lxx_value (or None when not reviewed)
EXPLICIT = [
    ("Joshua", "moses' assistant", "lifespan", 110, "Joshua 24:29; Judges 2:8", None),
    ("Caleb@Num.13.6-1Ch", "", "age_at_event", 40, "Joshua 14:7", "Age when Moses sent him from Kadesh-barnea to spy out the land."),
    ("Caleb@Num.13.6-1Ch", "", "age_at_event", 85, "Joshua 14:10", "Age when he asked Joshua for Hebron, forty-five years later."),
    ("Eli", "", "lifespan", 98, "1 Samuel 4:15", "He was 98 when he died on hearing the ark was captured (1 Samuel 4:18)."),
    ("Eli", "", "judged_years", 40, "1 Samuel 4:18", "The Septuagint (1 Reigns 4:18) reads twenty years."),
    ("Barzillai", "gileadite", "age_at_event", 80, "2 Samuel 19:32,35", None),
    ("Mephibosheth", "jonathan", "age_at_event", 5, "2 Samuel 4:4", "Age when news came of Saul's and Jonathan's deaths."),
    ("Jehoiada", "priest", "lifespan", 130, "2 Chronicles 24:15", None),
    ("Job", "", "years_after_restoration", 140, "Job 42:16", "The Old Greek reads 170 years after the affliction and 240 years in all."),
    ("Othniel", "", "rest_years", 40, "Judges 3:11", "The land had rest forty years."),
    ("Ehud@Jdg.3.15-1Ch", "", "rest_years", 80, "Judges 3:30", "The land had rest eighty years."),
    ("Deborah", "judge", "rest_years", 40, "Judges 5:31", "The land had rest forty years."),
    ("Gideon", "", "rest_years", 40, "Judges 8:28", "The land had rest forty years in Gideon's days."),
    ("Abimelech", "gideon", "reign_years", 3, "Judges 9:22", None),
    ("Tola", "judge", "judged_years", 23, "Judges 10:2", None),
    ("Jair", "judge", "judged_years", 22, "Judges 10:3", None),
    ("Jephthah", "", "judged_years", 6, "Judges 12:7", None),
    ("Ibzan", "", "judged_years", 7, "Judges 12:9", None),
    ("Elon", "judge", "judged_years", 10, "Judges 12:11", None),
    ("Abdon", "judge", "judged_years", 8, "Judges 12:14", None),
    ("Samson", "", "judged_years", 20, "Judges 15:20; 16:31", None),
    ("Cushan-rishathaim", "", "oppression_years", 8, "Judges 3:8", None),
    ("Eglon", "moab", "oppression_years", 18, "Judges 3:14", None),
    ("Jabin@Jdg.4.2-Psa", "", "oppression_years", 20, "Judges 4:3", "Jabin of Judges 4; distinct from the Jabin of Joshua 11 unless the identification is made explicit."),
]

# ------------------------------------------------------------------ dated events
# id, book, chapter range, name, type, verse, relative date value (dict) or None, display year BCE, note, participant names [(name, keyword)]
DATED_EVENTS = [
    ("solomon-temple-founded", "1Ki", (6, 6), "Solomon begins building the temple", "construction", "1 Kings 6:1",
     {"kind": "relative_date", "reference_event": "passover-and-departure", "year_number": 480, "month_number": 2},
     966, "The Septuagint (3 Reigns 6:1) reads the 440th year. The verse also dates the founding to Solomon's fourth year.",
     [("Solomon", "")]),
    ("kingdom-divides", "1Ki", (12, 12), "The northern tribes reject Rehoboam and make Jeroboam king", "succession", "1 Kings 12:1-20",
     None, 931, None, [("Rehoboam", ""), ("Jeroboam", "first king")]),
    ("shishak-invades-judah", "1Ki", (14, 14), "Shishak of Egypt attacks Jerusalem", "battle", "1 Kings 14:25-26; 2 Chronicles 12:2",
     {"kind": "regnal_date", "king": "Rehoboam", "year_number": 5}, 926, None, [("Shishak", ""), ("Rehoboam", "")]),
    ("fall-of-samaria", "2Ki", (17, 18), "Samaria falls to Assyria and Israel is exiled", "battle", "2 Kings 17:6; 18:9-10",
     {"kind": "regnal_date", "king": "Hoshea", "year_number": 9}, 722,
     "2 Kings 18:10 synchronizes the fall with Hezekiah's sixth year.", [("Hoshea", "king of israel"), ("Shalmaneser", "")]),
    ("sennacherib-invades-judah", "2Ki", (18, 19), "Sennacherib invades Judah and besieges Jerusalem", "battle", "2 Kings 18:13; Isaiah 36:1",
     {"kind": "regnal_date", "king": "Hezekiah", "year_number": 14}, 701, None, [("Sennacherib", ""), ("Hezekiah", "king of judah")]),
    ("josiah-finds-the-law", "2Ki", (22, 23), "The book of the law is found and Josiah reforms worship", "reform", "2 Kings 22:3",
     {"kind": "regnal_date", "king": "Josiah", "year_number": 18}, 622, None, [("Josiah", "king of judah"), ("Hilkiah", "high priest")]),
    ("jehoiachin-exiled", "2Ki", (24, 24), "Jehoiachin surrenders and is taken to Babylon", "exile", "2 Kings 24:12",
     {"kind": "regnal_date", "king": "Nebuchadnezzar", "year_number": 8}, 597, None, [("Jehoiachin", ""), ("Nebuchadnezzar", "")]),
    ("jerusalem-burned", "2Ki", (25, 25), "Nebuzaradan burns the temple and Jerusalem", "battle", "2 Kings 25:8",
     {"kind": "regnal_date", "king": "Nebuchadnezzar", "year_number": 19, "month_number": 5, "day_number": 7}, 586,
     "Jeremiah 52:12 gives the tenth day of the fifth month; both readings are retained.", [("Nebuzaradan", ""), ("Zedekiah", "last king")]),
    ("jehoiachin-released", "2Ki", (25, 25), "Evil-merodach releases Jehoiachin from prison", "release", "2 Kings 25:27",
     {"kind": "relative_date", "reference_event": "jehoiachin-exiled", "year_number": 37, "month_number": 12, "day_number": 27}, 561,
     "Jeremiah 52:31 gives the twenty-fifth day of the month.", [("Jehoiachin", ""), ("Evil-merodach", "")]),
    ("cyrus-decree", "Ezr", (1, 1), "Cyrus decrees the rebuilding of the temple", "decree", "Ezra 1:1; 2 Chronicles 36:22",
     {"kind": "regnal_date", "king": "Cyrus", "year_number": 1}, 538, None, [("Cyrus", "")]),
    ("second-temple-completed", "Ezr", (6, 6), "The rebuilt temple is completed", "construction", "Ezra 6:15",
     {"kind": "regnal_date", "king": "Darius", "year_number": 6, "month_number": 12, "day_number": 3}, 515, None, [("Darius@Ezr.4.5-Zec", ""), ("Zerubbabel", "")]),
    ("ezra-arrives-jerusalem", "Ezr", (7, 7), "Ezra arrives in Jerusalem", "migration", "Ezra 7:8-9",
     {"kind": "regnal_date", "king": "Artaxerxes", "year_number": 7, "month_number": 5, "day_number": 1}, 458, None, [("Ezra", "scribe"), ("Artaxerxes", "")]),
    ("nehemiah-commissioned", "Neh", (2, 2), "Artaxerxes sends Nehemiah to rebuild Jerusalem", "commission", "Nehemiah 2:1",
     {"kind": "regnal_date", "king": "Artaxerxes", "year_number": 20, "month_number": 1}, 445, None, [("Nehemiah", "governor"), ("Artaxerxes", "")]),
    ("jerusalem-wall-completed", "Neh", (6, 6), "The wall of Jerusalem is completed in fifty-two days", "construction", "Nehemiah 6:15",
     {"kind": "regnal_date", "king": "Artaxerxes", "year_number": 20, "month_number": 6, "day_number": 25}, 445,
     "The text gives the twenty-fifth of Elul; the regnal year is inferred from Nehemiah 2:1.", [("Nehemiah", "governor")]),
    ("esther-made-queen", "Est", (2, 2), "Esther is made queen", "coronation", "Esther 2:16-17",
     {"kind": "regnal_date", "king": "Ahasuerus", "year_number": 7, "month_number": 10}, 479, None, [("Esther", ""), ("Ahasuerus", "esther")]),
    ("purim-deliverance", "Est", (9, 9), "The Jews defend themselves on the thirteenth of Adar; Purim instituted", "deliverance", "Esther 9:1,17-19",
     {"kind": "regnal_date", "king": "Ahasuerus", "year_number": 12, "month_number": 12, "day_number": 13}, 473,
     "The regnal year is inferred from Esther 3:7.", [("Esther", ""), ("Mordecai", "esther")]),
    ("haggai-first-oracle", "Hag", (1, 1), "Haggai urges the rebuilding of the temple", "prophecy", "Haggai 1:1",
     {"kind": "regnal_date", "king": "Darius", "year_number": 2, "month_number": 6, "day_number": 1}, 520, None, [("Haggai", ""), ("Zerubbabel", "")]),
    ("ezekiel-call", "Ezk", (1, 1), "Ezekiel's vision by the Chebar canal", "call", "Ezekiel 1:1-2",
     {"kind": "relative_date", "reference_event": "jehoiachin-exiled", "year_number": 5, "month_number": 4, "day_number": 5}, 593,
     "Ezekiel 1:1 also speaks of 'the thirtieth year', whose reference point is disputed.", [("Ezekiel", "")]),
    ("isaiah-temple-vision", "Isa", (6, 6), "Isaiah's temple vision in the year King Uzziah died", "call", "Isaiah 6:1",
     None, 740, None, [("Isaiah", ""), ("Uzziah@2Ki.14.21-Mat", "")]),
    ("jeremiah-call", "Jer", (1, 1), "Jeremiah is called as a prophet", "call", "Jeremiah 1:2",
     {"kind": "regnal_date", "king": "Josiah", "year_number": 13}, 627, None, [("Jeremiah", "prophet")]),
    ("daniel-taken-to-babylon", "Dan", (1, 1), "Daniel and his companions taken to Babylon", "exile", "Daniel 1:1",
     {"kind": "regnal_date", "king": "Jehoiakim", "year_number": 3}, 605,
     "Jeremiah 25:1 equates Jehoiakim's fourth year with Nebuchadnezzar's first; the difference is usually explained by accession-year reckoning.",
     [("Daniel@Ezk.14.14-Mrk", ""), ("Nebuchadnezzar", ""), ("Jehoiakim", "")]),
    ("fall-of-babylon-belshazzar", "Dan", (5, 5), "Belshazzar's feast and the fall of Babylon", "battle", "Daniel 5:30-31",
     None, 539, None, [("Belshazzar", ""), ("Daniel@Ezk.14.14-Mrk", "")]),
]

# ------------------------------------------------------------------ section events per book
SECTIONS = {
    "Jos": [(1, 5, "Israel crosses the Jordan into Canaan", "migration"), (6, 8, "Fall of Jericho and Ai", "battle"),
            (9, 12, "Gibeonite treaty and the southern and northern campaigns", "battle"), (13, 21, "Land allotted to the tribes", "allotment"),
            (22, 22, "The eastern tribes' altar by the Jordan", "narrative"), (23, 24, "Joshua's farewell and covenant at Shechem", "covenant")],
    "Jdg": [(1, 2, "Incomplete conquest and the cycle of the judges", "narrative"), (3, 3, "Othniel, Ehud, and Shamgar deliver Israel", "deliverance"),
            (4, 5, "Deborah and Barak defeat Sisera", "battle"), (6, 8, "Gideon delivers Israel from Midian", "deliverance"),
            (9, 9, "Abimelech's rule at Shechem", "narrative"), (10, 12, "Tola, Jair, Jephthah, Ibzan, Elon, and Abdon", "deliverance"),
            (13, 16, "Samson and the Philistines", "deliverance"), (17, 18, "Micah's shrine and the Danite migration", "narrative"),
            (19, 21, "Outrage at Gibeah and war with Benjamin", "battle")],
    "Rut": [(1, 4, "Ruth and Naomi; Boaz redeems", "narrative")],
    "1Sa": [(1, 3, "Birth and call of Samuel", "narrative"), (4, 7, "Ark captured and returned; Samuel judges Israel", "narrative"),
            (8, 12, "Israel asks for a king; Saul made king", "succession"), (13, 15, "Saul's wars and rejection", "battle"),
            (16, 17, "David anointed; David and Goliath", "narrative"), (18, 26, "Saul pursues David", "narrative"),
            (27, 30, "David among the Philistines; the medium of Endor", "narrative"), (31, 31, "Saul and his sons die on Gilboa", "death")],
    "2Sa": [(1, 4, "David king at Hebron; war with Saul's house", "succession"), (5, 10, "David reigns over all Israel from Jerusalem", "succession"),
            (11, 12, "David, Bathsheba, and Uriah", "narrative"), (13, 19, "Amnon, Absalom, and Absalom's revolt", "narrative"),
            (20, 20, "Sheba's revolt", "narrative"), (21, 24, "Famine, mighty men, census, and plague", "narrative")],
    "1Ki": [(1, 2, "Solomon succeeds David", "succession"), (3, 4, "Solomon's wisdom and administration", "narrative"),
            (5, 8, "Temple and palace built and dedicated", "construction"), (9, 11, "Solomon's glory, wives, and adversaries", "narrative"),
            (12, 14, "The kingdom divides: Rehoboam and Jeroboam", "succession"), (15, 16, "Kings from Abijam to Ahab", "succession"),
            (17, 19, "Elijah, the drought, and Carmel", "narrative"), (20, 22, "Ahab's wars, Naboth's vineyard, and Ahab's death", "battle")],
    "2Ki": [(1, 2, "Ahaziah's death; Elijah taken up", "narrative"), (3, 8, "Elisha's ministry", "narrative"), (9, 10, "Jehu's revolt", "succession"),
            (11, 12, "Athaliah overthrown; Joash reigns", "succession"), (13, 16, "Kings of Israel and Judah to Ahaz", "succession"),
            (17, 17, "Fall of Samaria and exile of Israel", "battle"), (18, 20, "Hezekiah, Sennacherib, and Isaiah", "narrative"),
            (21, 23, "Manasseh, Amon, and Josiah's reform", "narrative"), (24, 25, "Babylonian conquest and the fall of Jerusalem", "battle")],
    "1Ch": [(1, 9, "Genealogies from Adam to the returned exiles", "genealogy"), (10, 10, "Death of Saul", "death"),
            (11, 12, "David made king; his mighty men", "succession"), (13, 16, "The ark brought to Jerusalem", "narrative"),
            (17, 21, "Covenant with David; wars; census", "narrative"), (22, 29, "Temple preparations and Solomon's accession", "succession")],
    "2Ch": [(1, 9, "Solomon's reign and temple", "construction"), (10, 12, "Rehoboam and the division", "succession"), (13, 16, "Abijah and Asa", "succession"),
            (17, 20, "Jehoshaphat", "narrative"), (21, 24, "Jehoram, Ahaziah, Athaliah, and Joash", "succession"),
            (25, 28, "Amaziah, Uzziah, Jotham, and Ahaz", "succession"), (29, 32, "Hezekiah's reform and deliverance", "narrative"),
            (33, 35, "Manasseh, Amon, and Josiah", "narrative"), (36, 36, "The last kings, exile, and Cyrus's decree", "narrative")],
    "Ezr": [(1, 2, "Cyrus's decree and the first return", "migration"), (3, 6, "Temple rebuilt despite opposition", "construction"),
            (7, 8, "Ezra's return", "migration"), (9, 10, "Mixed marriages dissolved", "narrative")],
    "Neh": [(1, 7, "Nehemiah rebuilds Jerusalem's wall", "construction"), (8, 10, "The law read; covenant renewed", "covenant"),
            (11, 12, "Jerusalem repopulated; the wall dedicated", "narrative"), (13, 13, "Nehemiah's later reforms", "narrative")],
    "Est": [(1, 2, "Vashti deposed; Esther made queen", "narrative"), (3, 7, "Haman's plot and Esther's intercession", "narrative"),
            (8, 10, "The Jews delivered; Purim", "narrative")],
    "Job": [(1, 2, "Job's trials", "narrative"), (3, 31, "Job and his friends dispute", "speech"), (32, 37, "Elihu's speeches", "speech"),
            (38, 42, "The LORD answers; Job restored", "narrative")],
    "Psa": [(1, 41, "Psalms, Book I", "poetry"), (42, 72, "Psalms, Book II", "poetry"), (73, 89, "Psalms, Book III", "poetry"),
            (90, 106, "Psalms, Book IV", "poetry"), (107, 150, "Psalms, Book V", "poetry")],
    "Pro": [(1, 9, "Instruction in wisdom", "wisdom"), (10, 29, "Proverbs of Solomon and the wise", "wisdom"), (30, 31, "Words of Agur and King Lemuel", "wisdom")],
    "Ecc": [(1, 12, "Words of the Preacher", "wisdom")],
    "Sng": [(1, 8, "The Song of Songs", "poetry")],
    "Isa": [(1, 12, "Oracles concerning Judah and Jerusalem", "prophecy"), (13, 23, "Oracles against the nations", "prophecy"),
            (24, 35, "Judgment and salvation oracles", "prophecy"), (36, 39, "Hezekiah, Sennacherib, and Isaiah", "narrative"),
            (40, 55, "Comfort for Israel and the servant of the LORD", "prophecy"), (56, 66, "Closing oracles of judgment and new creation", "prophecy")],
    "Jer": [(1, 1, "Jeremiah's call", "call"), (2, 25, "Oracles against Judah and Jerusalem", "prophecy"),
            (26, 29, "Jeremiah's conflicts with priests and prophets", "narrative"), (30, 33, "The book of consolation", "prophecy"),
            (34, 39, "Siege and fall of Jerusalem", "narrative"), (40, 45, "After the fall; the flight to Egypt", "narrative"),
            (46, 51, "Oracles against the nations", "prophecy"), (52, 52, "Fall of Jerusalem and Jehoiachin's release", "narrative")],
    "Lam": [(1, 5, "Laments over Jerusalem", "poetry")],
    "Ezk": [(1, 3, "Ezekiel's call by the Chebar canal", "call"), (4, 24, "Judgment on Jerusalem", "prophecy"),
            (25, 32, "Oracles against the nations", "prophecy"), (33, 39, "Restoration oracles", "prophecy"), (40, 48, "The temple vision", "vision")],
    "Dan": [(1, 1, "Daniel and his friends in Babylon", "narrative"), (2, 4, "Nebuchadnezzar's dreams and the fiery furnace", "narrative"),
            (5, 5, "Belshazzar's feast", "narrative"), (6, 6, "Daniel in the lions' den", "narrative"), (7, 12, "Daniel's visions", "vision")],
    "Hos": [(1, 14, "Hosea's marriage and oracles", "prophecy")], "Jol": [(1, 3, "Joel's oracles of the locusts and the day of the LORD", "prophecy")],
    "Amo": [(1, 9, "Amos's oracles against Israel and the nations", "prophecy")], "Oba": [(1, 1, "Obadiah's oracle against Edom", "prophecy")],
    "Jon": [(1, 4, "Jonah's flight and Nineveh's repentance", "narrative")], "Mic": [(1, 7, "Micah's oracles", "prophecy")],
    "Nam": [(1, 3, "Nahum's oracle against Nineveh", "prophecy")], "Hab": [(1, 3, "Habakkuk's complaint and prayer", "prophecy")],
    "Zep": [(1, 3, "Zephaniah's oracles of the day of the LORD", "prophecy")], "Hag": [(1, 2, "Haggai's temple oracles", "prophecy")],
    "Zec": [(1, 8, "Zechariah's night visions and oracles", "vision"), (9, 14, "Zechariah's later oracles", "prophecy")],
    "Mal": [(1, 4, "Malachi's disputations", "prophecy")],
}

# ------------------------------------------------------------------ unnamed but uniquely identifiable individuals not in TIPNR
# id, name, gender, refs [(book, chapter, verse)], description, parents [(name, keyword) or our-id], death_narrated
UNNAMED = [
    ("man-of-luz", "Man of Luz who showed the way into the city", "male", [("Jdg", 1, 24)], "Spared for showing the spies the entrance to Luz (Bethel); he founded a new Luz (Judges 1:24-26).", []),
    ("sisera-mother", "Sisera's mother", "female", [("Jdg", 5, 28)], "Waits at the window for Sisera's return in the Song of Deborah (Judges 5:28-30).", []),
    ("unnamed-prophet-judges-6", "Prophet sent before Gideon's call", "male", [("Jdg", 6, 8)], "Unnamed prophet who rebuked Israel before Gideon's call (Judges 6:8-10).", []),
    ("gideon-concubine-shechem", "Gideon's concubine in Shechem", "female", [("Jdg", 8, 31)], "Mother of Abimelech (Judges 8:31).", []),
    ("woman-of-thebez", "Woman of Thebez", "female", [("Jdg", 9, 53)], "Dropped a millstone on Abimelech's head (Judges 9:53).", []),
    ("abimelech-armor-bearer", "Abimelech's armor-bearer", "male", [("Jdg", 9, 54)], "Killed Abimelech at his command (Judges 9:54).", []),
    ("jephthah-daughter", "Jephthah's daughter", "female", [("Jdg", 11, 34)], "Jephthah's only child, subject of his vow (Judges 11:34-40).", [("Jephthah", "")]),
    ("manoah-wife", "Manoah's wife", "female", [("Jdg", 13, 2)], "Mother of Samson; visited by the angel of the LORD (Judges 13).", []),
    ("samson-timnite-wife", "Samson's Timnite wife", "female", [("Jdg", 14, 1)], "Philistine woman of Timnah married to Samson; later burned with her father (Judges 14-15).", []),
    ("samson-timnite-father-in-law", "Father of Samson's Timnite wife", "male", [("Jdg", 15, 1)], "Gave his daughter to Samson's companion; burned by the Philistines (Judges 15:1-6).", []),
    ("micah-mother", "Micah's mother", "female", [("Jdg", 17, 2)], "Dedicated silver for the image in Micah's shrine (Judges 17:2-4).", []),
    ("levite-of-ephraim", "Levite of the hill country of Ephraim", "male", [("Jdg", 19, 1)], "Levite whose concubine was murdered at Gibeah (Judges 19-20).", []),
    ("levite-concubine", "The Levite's concubine", "female", [("Jdg", 19, 1)], "Woman of Bethlehem abused and killed at Gibeah (Judges 19).", []),
    ("levite-concubine-father", "Father of the Levite's concubine", "male", [("Jdg", 19, 3)], "Her father in Bethlehem who hosted the Levite (Judges 19:3-9).", []),
    ("old-man-of-gibeah", "Old man of Gibeah", "male", [("Jdg", 19, 16)], "Ephraimite who sheltered the Levite in Gibeah (Judges 19:16-24).", []),
    ("nearer-redeemer-ruth", "The nearer redeemer", "male", [("Rut", 3, 12), ("Rut", 4, 1)], "Kinsman closer than Boaz who declined to redeem (Ruth 4:1-8).", []),
    ("man-of-god-to-eli", "Man of God who came to Eli", "male", [("1Sa", 2, 27)], "Pronounced judgment on Eli's house (1 Samuel 2:27-36).", []),
    ("benjaminite-messenger-shiloh", "Benjaminite who brought news to Shiloh", "male", [("1Sa", 4, 12)], "Brought Eli news of the ark's capture (1 Samuel 4:12-17).", []),
    ("phinehas-wife", "Wife of Phinehas son of Eli", "female", [("1Sa", 4, 19)], "Mother of Ichabod; died in childbirth (1 Samuel 4:19-22).", []),
    ("saul-servant-donkeys", "Saul's servant on the search for the donkeys", "male", [("1Sa", 9, 3)], "Suggested consulting the seer (1 Samuel 9).", []),
    ("jonathan-armor-bearer", "Jonathan's armor-bearer", "male", [("1Sa", 14, 1)], "Accompanied Jonathan against the Philistine garrison (1 Samuel 14).", []),
    ("medium-of-endor", "Medium of Endor", "female", [("1Sa", 28, 7)], "Woman consulted by Saul before Gilboa (1 Samuel 28).", []),
    ("egyptian-servant-ziklag", "Egyptian servant of an Amalekite", "male", [("1Sa", 30, 11)], "Led David to the Amalekite raiders (1 Samuel 30:11-16).", []),
    ("amalekite-who-reported-saul", "Amalekite who reported Saul's death", "male", [("2Sa", 1, 2)], "Claimed to have killed Saul; executed by David (2 Samuel 1).", []),
    ("mephibosheth-nurse", "Mephibosheth's nurse", "female", [("2Sa", 4, 4)], "Dropped Mephibosheth while fleeing (2 Samuel 4:4).", []),
    ("bathsheba-first-son", "First son of David and Bathsheba", "male", [("2Sa", 12, 15)], "Died seven days after falling ill (2 Samuel 12:15-23).", [("David", "king"), ("Bathsheba", "")]),
    ("wise-woman-of-tekoa", "Wise woman of Tekoa", "female", [("2Sa", 14, 2)], "Brought Joab's petition for Absalom's return (2 Samuel 14).", []),
    ("cushite-messenger", "The Cushite messenger", "male", [("2Sa", 18, 21)], "Brought David news of Absalom's death (2 Samuel 18:21-32).", []),
    ("wise-woman-of-abel", "Wise woman of Abel Beth-maacah", "female", [("2Sa", 20, 16)], "Negotiated Sheba's death to save her city (2 Samuel 20:16-22).", []),
    ("mother-of-living-child", "Mother of the living child before Solomon", "female", [("1Ki", 3, 16)], "One of two women whose case Solomon judged (1 Kings 3:16-27).", []),
    ("mother-of-dead-child", "Mother of the dead child before Solomon", "female", [("1Ki", 3, 16)], "The other woman in Solomon's judgment (1 Kings 3:16-27).", []),
    ("man-of-god-from-judah", "Man of God from Judah", "male", [("1Ki", 13, 1)], "Prophesied against the altar at Bethel and was killed by a lion (1 Kings 13).", []),
    ("old-prophet-of-bethel", "Old prophet of Bethel", "male", [("1Ki", 13, 11)], "Deceived the man of God from Judah and buried him (1 Kings 13).", []),
    ("jeroboam-wife", "Jeroboam's wife", "female", [("1Ki", 14, 2)], "Disguised herself to consult Ahijah about her son (1 Kings 14).", []),
    ("widow-of-zarephath", "Widow of Zarephath", "female", [("1Ki", 17, 9)], "Fed Elijah during the drought (1 Kings 17).", []),
    ("son-of-widow-of-zarephath", "Son of the widow of Zarephath", "male", [("1Ki", 17, 17)], "Restored to life by Elijah (1 Kings 17:17-24).", ["widow-of-zarephath"]),
    ("wounded-prophet-1ki20", "Prophet who rebuked Ahab in disguise", "male", [("1Ki", 20, 35)], "One of the sons of the prophets who condemned Ahab's release of Ben-hadad (1 Kings 20:35-43).", []),
    ("widow-of-prophet-oil", "Widow whose oil was multiplied", "female", [("2Ki", 4, 1)], "Widow of one of the sons of the prophets (2 Kings 4:1-7).", []),
    ("shunammite-woman", "Shunammite woman", "female", [("2Ki", 4, 8), ("2Ki", 8, 1)], "Hosted Elisha; her son was raised; her land restored (2 Kings 4; 8).", []),
    ("shunammite-husband", "Husband of the Shunammite woman", "male", [("2Ki", 4, 9)], "Older husband of the Shunammite woman (2 Kings 4).", []),
    ("shunammite-son", "Son of the Shunammite woman", "male", [("2Ki", 4, 17)], "Born as Elisha foretold and raised to life (2 Kings 4).", ["shunammite-woman", "shunammite-husband"]),
    ("naaman-servant-girl", "Israelite servant girl of Naaman's wife", "female", [("2Ki", 5, 2)], "Captive girl who pointed Naaman to Elisha (2 Kings 5:2-4).", []),
    ("naaman-wife", "Naaman's wife", "female", [("2Ki", 5, 2)], "Wife of Naaman the Aramean commander (2 Kings 5:2).", []),
    ("samaria-siege-mother", "Mother who appealed to the king during the siege of Samaria", "female", [("2Ki", 6, 26)], "Woman whose plea revealed the famine's horror (2 Kings 6:26-30).", []),
    ("samaria-royal-officer", "Officer on whose arm the king leaned", "male", [("2Ki", 7, 2)], "Doubted Elisha's word and was trampled at the gate (2 Kings 7:2,17-20).", []),
    ("young-prophet-anointing-jehu", "Young prophet who anointed Jehu", "male", [("2Ki", 9, 4)], "Sent by Elisha to anoint Jehu at Ramoth-gilead (2 Kings 9:4-10).", []),
    ("job-wife", "Job's wife", "female", [("Job", 2, 9)], "Spoke to Job after his affliction (Job 2:9; 19:17).", []),
    ("isaiah-wife-prophetess", "The prophetess, Isaiah's wife", "female", [("Isa", 8, 3)], "Mother of Maher-shalal-hash-baz (Isaiah 8:3).", []),
    ("jonah-ship-captain", "Captain of Jonah's ship", "male", [("Jon", 1, 6)], "Woke Jonah during the storm (Jonah 1:6).", []),
    ("king-of-nineveh", "King of Nineveh", "male", [("Jon", 3, 6)], "Proclaimed Nineveh's fast at Jonah's preaching (Jonah 3:6-9).", []),
    ("queen-mother-belshazzar", "The queen at Belshazzar's feast", "female", [("Dan", 5, 10)], "Recommended Daniel to interpret the writing (Daniel 5:10-12).", []),
]

# Named people missing or merged in TIPNR, handled like the unnamed list but classified as named.
NAMED_EXTRA = [
    ("sargon-ii", "Sargon", "male", [("Isa", 20, 1)], "Sargon II of Assyria, who sent his commander against Ashdod (Isaiah 20:1); TIPNR merges this name with Sennacherib.", []),
    ("ahasuerus-dan9", "Ahasuerus, father of Darius the Mede", "male", [("Dan", 9, 1)],
     "Named only as the Median father of Darius (Daniel 9:1); kept distinct from the Persian Ahasuerus of Esther and Ezra 4:6.", []),
]
UNNAMED.append(("tartan-of-sargon", "Sargon's commander-in-chief (the tartan) at Ashdod", "male", [("Isa", 20, 1)],
                "Assyrian commander sent by Sargon against Ashdod (Isaiah 20:1); distinct from Sennacherib's tartan (2 Kings 18:17).", []))
# Verse references removed from TIPNR persons because they belong to a different individual.
# Eponymous ancestors whose names mostly denote a tribe, nation, or clan after Genesis. Outside the Pentateuch their
# references are kept only where they are named as individuals in genealogies; nation/tribe usages are not person mentions.
EPONYMS = {"jacob", "judah", "ephraim", "benjamin", "manasseh", "levi", "reuben", "gad", "naphtali", "zebulun", "asher",
           "issachar", "simeon", "dan", "joseph", "shechem", "kedar", "merari", "kohath", "gershon", "korah-levite", "machir"}
EPONYM_LATER_CONTEXTS = {("1Ch", c) for c in list(range(1, 10)) + [23]} | {("Rut", 4)}
REF_DROP_VERSE = {("Jethro@Exo.2.18-Num", "Num", 10, 29), ("Sennacherib@2Ki.18.13-Isa", "Isa", 20, 1), ("Tartan@2Ki.18.17-Isa", "Isa", 20, 1), ("Ahasuerus@Ezr.4.6-Dan", "Dan", 9, 1)}

# Parent links for curated unnamed people that need a TIPNR child: (parent our-id, (child name, keyword))
UNNAMED_PARENT_OF = [
    ("manoah-wife", ("Samson", "")), ("gideon-concubine-shechem", ("Abimelech", "gideon")),
    ("phinehas-wife", ("Ichabod", "")), ("jeroboam-wife", ("Abijah", "jeroboam")),
    ("samson-timnite-father-in-law", "samson-timnite-wife"), ("levite-concubine-father", "levite-concubine"),
    ("isaiah-wife-prophetess", ("Maher-shalal-hash-baz", "")),
    ("ahasuerus-dan9", ("Darius@Dan.5.31-", "")),
]
# Explicit parent links TIPNR cannot see because the parent speaks in the first person: (parent, child, verse)
FIRST_PERSON_PARENTS = [(("Isaiah", ""), ("Maher-shalal-hash-baz", ""), ("Isa", 8, 3))]
# TIPNR records that are the same person (target keeps the identity): source uid -> target uid
MERGE_UIDS = {"Shallum@1Ch.3.15": "Jehoahaz@2Ki.23.30-2Ch"}  # Jeremiah 22:11 calls Jehoahaz 'Shallum son of Josiah' 
# Spouse links for curated unnamed people: (a, b) where each is an our-id or (name, keyword)
UNNAMED_SPOUSES = [
    (("Manoah", ""), "manoah-wife"), (("Samson", ""), "samson-timnite-wife"), (("Phinehas", "eli"), "phinehas-wife"),
    (("Jeroboam", "first king"), "jeroboam-wife"), (("Naaman", "aram"), "naaman-wife"), ("shunammite-husband", "shunammite-woman"),
    (("Job", ""), "job-wife"), (("Isaiah", ""), "isaiah-wife-prophetess"), ("levite-of-ephraim", "levite-concubine"),
    (("Gideon", ""), "gideon-concubine-shechem"),
]

# People whose LXX/Ge'ez presence is asserted (book level, grade C) when they have at least this many references in a book.
VERSION_PRESENCE_MIN_REFS = 10
